[project]
name = "redcap-alert-handler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nate Vack", email = "njvack@wisc.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "rust-just>=1.55.1",
]

[project.scripts]
redcap-alert-handler = "redcap_alert_handler:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
